import type { Metadata } from "next";
import { Geist, Geist_Mono, Nova_Cut } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const novaCut = Nova_Cut({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nova-cut",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Fill in with actual webpage links when they are done.
const navigationLinks = [
  {label: "Home", href: "/"},
  {label: "About", href: "/"}, 
  {label: "Our Games", href: "/"}
]

// Add whichever socials Rapture wants here.
const externalLinks = [
  { label: "Twitter", href: "https://twitter.com" },
  { label: "Discord", href: "https://discord.com" },
  { label: "Instagram", href: "https://instagram.com"}
];

// Add any additional text.
const title = "Xavier Miller";
const desc = "SWE Engineer";
const text1 = "Want to be notified of our upcoming games!";
const text2 = "Make sure to follow us on our socials.";
const copyright = "© 2026 Studio Rapture. All rights reserved.";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${novaCut.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
